apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homepage-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - www.paulme.ng
    - paulme.ng
    secretName: letsencrypt-prod
  rules:
  - host: www.paulme.ng
    http:
      paths:
      - backend:
          serviceName: homepage
          servicePort: 80
